### PR TITLE
Support for PU reweighting

### PR DESCRIPTION
**Pull request by ndefilip**
PUreweighting

### CODE REVIEW

**Review by jsturdy — COMMENTED** [review]
Thanks @ndefilip! Is this already done for the electrons?  Or does it need to be added there as well?

**Comment by ndefilip** [comment]
I can add that for electrons too…

cheers

Nic

Il giorno 17 gen 2018, alle ore 10:05, Jared Sturdy <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@jsturdy commented on this pull request.

Thanks @ndefilip<https://github.com/ndefilip>! Is this already done for the electrons? Or does it need to be added there as well?

**Comment by ndefilip** [comment]
Done for the electrons too

**Review by jsturdy — APPROVED** [review]
Thanks!

**Pull request merged**
